### ISSUE TITLE
Anyone seeing issues with Yosemite with LaunchD

### ISSUE THREAD

**Issue by CivZero** [Macdeviant/MacAppStoreRedist#1]
When I first installed the ServiceInstall.sh it worked beautifully, it appeared to have missed one but no big deal. For some reason everything has stopped, and watching the manifest.plist doesn't seem to be happening. I have tested the path that is laid out in the watch.plist and it appears to be working just fine. I am not sure its an issue with the LaunchDs of 10.10 or maybe something else. Also if this is the wrong place for this, please let me know and I will remove it promptly.

**Comment by MacsInSpace** [comment]
Logging it here is fine.
I'm curious as to what application was the one that it missed?
If the Application "Subtitle" is made by "Apple", it should pick it up.
( It's the :representations:$itemNumber:subtitle entry in the Manifests.plist )
If is does not say Apple, it discards it.
You could always remove that "If then else fi" section so that it runs for all applications. 

Add the test line back into the script "say lol" so you get an audible noise when the script is run.
Then open the AppStore and retry.

**Comment by CivZero** [comment]
Okay so it looks like, once I removed the If statement it started working just fine. I'm not hearing the "say lol", but who cares it's freaking working. Good job, this is going to be a huge time saver. You Rock!!!! Thanks again the effort you put into this, I am already starting to see the possibilities.
